services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB']
      interval: 5s
      timeout: 3s
      retries: 20

  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', '-q', 'check_running']
      interval: 5s
      timeout: 5s
      retries: 20

  api:
    image: ${IMAGE_REF}
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      PORT: 3000
      NODE_ENV: production
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-15m}
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      RABBITMQ_PREFETCH: ${RABBITMQ_PREFETCH:-10}
      ORDERS_MAX_ATTEMPTS: ${ORDERS_MAX_ATTEMPTS:-3}
      ORDERS_RETRY_BASE_DELAY_MS: ${ORDERS_RETRY_BASE_DELAY_MS:-1000}
      ORDERS_RETRY_MAX_DELAY_MS: ${ORDERS_RETRY_MAX_DELAY_MS:-30000}
      AWS_REGION: ${AWS_REGION:-eu-central-1}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET:-lesson9-files-private}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-}
    ports:
      - '${APP_PORT}:3000'

volumes:
  pgdata:
